---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  environments_path: ./test/environments
  data_bags_path: ./test/data_bags
  client_rb:
    environment: kitchen

# DC/OS only supports centos 7.x (and CoreOS)
platforms:
  - name: centos71
    driver_config:
      box: boxcutter/centos71
    attributes:
      system:
        primary_interface: enp0s8
  - name: centos72
    driver_config:
      box: boxcutter/centos72
    attributes:
      system:
        primary_interface: enp0s8

suites:
  - name: dcos-m
    run_list:
      - recipe[masala_dcos::default]
    driver:
      synced_folders:
        - [".shared_data", "/shared", mount_options: ["dmode=777,fmode=666"]]
      network:
      - ["private_network", {ip: "10.10.10.11"}]
      customize:
        memory: 2048
        cpus: 1
    attributes:
      system:
        short_hostname: 'dcos-m'
        static_hosts:
          10.10.10.11: dcos-m.kitchen.masalatest.com
          10.10.10.12: dcos-a1.kitchen.masalatest.com
          10.10.10.13: dcos-a2.kitchen.masalatest.com
          10.10.10.14: dcos-a3.kitchen.masalatest.com
      dcos:
        master_list: ['10.10.10.11']
        dcos_role: 'master'
  - name: dcos-a1
    run_list:
      - recipe[masala_dcos::default]
    driver:
      synced_folders:
        - [".shared_data", "/shared", mount_options: ["dmode=777,fmode=666"]]
      network:
      - ["private_network", {ip: "10.10.10.12"}]
      customize:
        memory: 3072
        cpus: 1
    attributes:
      system:
        short_hostname: 'dcos-a1'
        static_hosts:
          10.10.10.11: dcos-m.kitchen.masalatest.com
          10.10.10.12: dcos-a1.kitchen.masalatest.com
          10.10.10.13: dcos-a2.kitchen.masalatest.com
          10.10.10.14: dcos-a3.kitchen.masalatest.com
      dcos:
        master_list: ['10.10.10.11']
        dcos_role: 'slave'
  - name: dcos-a2
    run_list:
      - recipe[masala_dcos::default]
    driver:
      synced_folders:
        - [".shared_data", "/shared", mount_options: ["dmode=777,fmode=666"]]
      network:
      - ["private_network", {ip: "10.10.10.13"}]
      customize:
        memory: 3072
        cpus: 1
    attributes:
      system:
        short_hostname: 'dcos-a2'
        static_hosts:
          10.10.10.11: dcos-m.kitchen.masalatest.com
          10.10.10.12: dcos-a1.kitchen.masalatest.com
          10.10.10.13: dcos-a2.kitchen.masalatest.com
          10.10.10.14: dcos-a3.kitchen.masalatest.com
      dcos:
        master_list: ['10.10.10.11']
        dcos_role: 'slave'
  - name: dcos-a3
    run_list:
      - recipe[masala_dcos::default]
    driver:
      synced_folders:
        - [".shared_data", "/shared", mount_options: ["dmode=777,fmode=666"]]
      network:
      - ["private_network", {ip: "10.10.10.14"}]
      customize:
        memory: 3072
        cpus: 1
    attributes:
      system:
        short_hostname: 'dcos-a3'
        static_hosts:
          10.10.10.11: dcos-m.kitchen.masalatest.com
          10.10.10.12: dcos-a1.kitchen.masalatest.com
          10.10.10.13: dcos-a2.kitchen.masalatest.com
          10.10.10.14: dcos-a3.kitchen.masalatest.com
      dcos:
        master_list: ['10.10.10.11']
        dcos_role: 'slave'

