---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  environments_path: ./test/environments
  data_bags_path: ./test/data_bags
  client_rb:
    environment: kitchen

platforms:
  - name: centos67
    driver_config:
      box: boxcutter/centos67
    attributes:
      system:
        primary_interface: eth1
  - name: centos71
    driver_config:
      box: boxcutter/centos71
    attributes:
      system:
        primary_interface: enp0s8
  - name: centos72
    driver_config:
      box: boxcutter/centos72
    attributes:
      system:
        primary_interface: enp0s8
  - name: ubuntu1404
    driver_config:
      box: boxcutter/ubuntu1404
    attributes:
      system:
        primary_interface: eth1
  - name: ubuntu1504
    driver_config:
      box: boxcutter/ubuntu1504
    attributes:
      system:
        primary_interface: eth1
  - name: debian82
    driver_config:
      box: boxcutter/debian82
    attributes:
      system:
        primary_interface: eth1

suites:
  - name: dcos-m
    run_list:
      - recipe[masala_dcos::default]
    driver:
      synced_folders:
        - [".shared_data", "/shared", mount_options: ["dmode=777,fmode=666"]]
      network:
      - ["private_network", {ip: "10.10.10.11"}]
      customize:
        memory: 3072
        cpus: 1
    attributes:
      system:
        short_hostname: 'dcos-m'
        static_hosts:
          10.10.10.11: dcos-m.kitchen.masalatest.com
          10.10.10.12: dcos-s.kitchen.masalatest.com
          10.10.10.13: dcos-p.kitchen.masalatest.com
      dcos:
        master_list: ['10.10.10.11']
        dcos_role: 'master'
  - name: dcos-s
    run_list:
      - recipe[masala_dcos::default]
    driver:
      synced_folders:
        - [".shared_data", "/shared", mount_options: ["dmode=777,fmode=666"]]
      network:
      - ["private_network", {ip: "10.10.10.12"}]
      customize:
        memory: 3072
        cpus: 1
    attributes:
      system:
        short_hostname: 'dcos-s'
        static_hosts:
          10.10.10.11: dcos-m.kitchen.masalatest.com
          10.10.10.12: dcos-s.kitchen.masalatest.com
          10.10.10.13: dcos-p.kitchen.masalatest.com
      dcos:
        master_list: ['10.10.10.11']
        dcos_role: 'slave'
  - name: dcos-p
    run_list:
      - recipe[masala_dcos::default]
    driver:
      synced_folders:
        - [".shared_data", "/shared", mount_options: ["dmode=777,fmode=666"]]
      network:
      - ["private_network", {ip: "10.10.10.13"}]
      customize:
        memory: 3072
        cpus: 1
    attributes:
      system:
        short_hostname: 'dcos-p'
        static_hosts:
          10.10.10.11: dcos-m.kitchen.masalatest.com
          10.10.10.12: dcos-s.kitchen.masalatest.com
          10.10.10.13: dcos-p.kitchen.masalatest.com
      dcos:
        master_list: ['10.10.10.11']
        dcos_role: 'slave_public'
