name             'masala_dcos'
maintainer       'Joe Hohertz'
maintainer_email 'jhohertz@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures masala_dcos'
long_description 'Installs/Configures masala_dcos'
version          '0.1.0'

depends          'masala_base', '~> 0.1.0'
depends          'dcos', '~> 0.2.0'
